debug: false
logging:
    level:
        com:
            hfut:
                beike:
                    dao: info
server:
    port: 8081
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: pscale_pw_7hRxdHLV5XZwHFkLjmF9KTbJarHQmsaWmNUeOf0K5m5
        url: jdbc:mysql://us-east.connect.psdb.cloud:3306/yugan2023?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=true
        username: tpb4do7goljbu6vrb66f
    thymeleaf:
        check-template-location: false
    data:
        mongodb:
            uri: mongodb+srv://yugan2023:20TJNV2HFxVaYnEr@cluster0.tqccyyb.mongodb.net/?retryWrites=true&w=majority
            database: test
minio:
    endpoint: https://minio.minio--r4h6xb4mrjyh.addon.code.run:443 #Minio服务所在地址
    bucketName: yugan2023 #存储桶名称
    accessKey: 90390e2d3d6fb9b97e #访问的key
    secretKey: 2f7a7b86b5f3d99d4d79d6ce8e29eb8f63f724 #访问的秘钥